### PR TITLE
Update

### PR DESCRIPTION
**Pull request by invisible1988**
Added reference to current Webcomponent. Usefull in callbacks from the swiper....

In that example i pass data to my "parent" webcomponent from the swiper:

paginationCustomRender: function (swiper, current, total) {
    this.currentComponent.currentSelected = current-1;
},

### CODE REVIEW

**Comment by ciampo** [comment]
Hi @pstreise,

could you write a more detailed use case for your pull request?
At the moment I can't see why you can't just refer to `this`, instead of setting `this.swiperOpts.currentComponent = this;`.

Thanks

**Comment by invisible1988** [comment]
If you referer to this you will get the instance of the swiper not of the component. e.g. i've implemented a custom pagination - so i need to access the Webcomponent to call a function dad change the pagination state.

Do you need more information? :)

Thanks

**Comment by invisible1988** [comment]
Hi @ciampo,
do you have seen my comment?

**Comment by ciampo** [comment]
Hi @pstreise ,

After reading your comment, I still think that the changes that you're proposing are unnecessary.

This is a Polymer 1.x behavior, which means that you need have a custom Polymer element that extends it. In the context of that custom element, the `this` value would refer to the custom element itself, while the `this.swiper` value would refer to the Swiper instance.

To show you what I mean, I temporarily added this little snippet of code to the demo in this repo:

```javascript
attached: function() {
  this._interval = setInterval(function() {
    if (this.initialised) {
      console.log('The value of "this" is:', this);
      console.log('The value of "this.swiper" is:', this.swiper);
      window.clearInterval(this._interval);
    }
  }.bind(this), 100);
},
```

This is the output of the console:
screen shot 2017-07-09 at 19 47 31


Please let me know if I'm still missing your point.

**Comment by invisible1988** [comment]
Hi @ciampo ,

I've created a custom navigation. In the "**paginationCustomRender**" callback I get with **this**  a reference to the swiper but not to the current webcomponent. I hope you can understand better my problem now.

image

**Comment by ciampo** [comment]
Hey @pstreise,

I now see your point. When using certain Swiper callbacks, the scope of the callback changes and you lose any reference to the Custom Element. 

Why don't you try doing this instead:

```javascript
attached: function() {
  this._interval = setInterval(function() {
    if (this.initialised) {
      this.setSwiperOption('paginationCustomRender',
        function (swiper, current, total) {
          console.log(this);
          // ... callback body
        }.bind(this));
      window.clearInterval(this._interval);
    }
  }.bind(this), 100);
},
```

the value of `this` should now be correct, since we can bind the callback correctly.

The main reason why I'm against the solution that you proposed, is because I don't want to pollute the Swiper options with custom properties. Ideally this should be a light wrapper around the Swiper APIs.

Let me know if this helps.

**Pull request closed without merging**
